<?php
/**
 * Created by PhpStorm.
 * User: EC_l
 * Date: 09.01.14
 * Time: 9:21
 * Email: bpteam22@gmail.com
 */
require_once dirname(__FILE__) . '/cnfg.php';
use GetContent\cCookie as cCookie;
echo "cCookie<br/>\n";

define('FILE_NAME', 'testCookies');
$functions = array(
	'create',
	'fromCurl',
	'fromFileCurl',
	'toCurl',
	'toFileCurl',
	'delete',
);

runTest($functions);

function create(){
	$cookie = new cCookie();
	$cookie->open(FILE_NAME);
	$cookie->create('testName', 'testValue', '.test1.ru', '/lib3', date('l, d-M-y H:i:s e', time() + 43200), false, false, true);
	$cookie->create('2testName', '2testValue', '.test1.ru', '/', date('l, d-M-y H:i:s e', time() + 63200), true, true, true);
	$cookies = $cookie->getCookies('http://www.test1.ru/blablalba/22');
	return $cookies['testName']['value'] == 'testValue' && $cookies['2testName']['value'] == '2testValue';
}

function fromCurl(){
	$curlCookie='# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.test1.ru	TRUE	/	FALSE	0	PHPSESSID	57f1bcb516082cbdbc1929331e0e7312
.test1.ru	TRUE	/	FALSE	1416569958	BITRIX_SM_GUEST_ID	87997
.test1.ru	TRUE	/	FALSE	1416569958	BITRIX_SM_LAST_VISIT	26.11.2013+15%3A39%3A18
.test1.ru	TRUE	/	FALSE	1416569702	BITRIX_SM_SALE_UID	753959';
	$cookie = new cCookie();
	$testCookie = $cookie->fromCurl($curlCookie);
	return ($testCookie['BITRIX_SM_GUEST_ID']['value'] == '87997' && $testCookie['PHPSESSID']['value'] == '57f1bcb516082cbdbc1929331e0e7312' && $testCookie['PHPSESSID']['httponly']);
}

function fromFileCurl(){
	$cookie = new cCookie();
	$cookie->open(FILE_NAME);
	$cookie->creates($cookie->fromFileCurl());
	$cookie->create('PHPSESSID', '57f1bcb516082cbdbc1929331e0e7312', '.test1.ru', '/', 0, true, false, true);
	$testCookie = $cookie->getCookies('test1.ru');
	return ($testCookie['BITRIX_SM_GUEST_ID']['value'] == '87997' && $testCookie['PHPSESSID']['value'] == '57f1bcb516082cbdbc1929331e0e7312' && $testCookie['PHPSESSID']['httponly']);
}

function toCurl(){
	$cookie = new cCookie();
	$cookie->open(FILE_NAME);
	$testCookie = $cookie->getCookies('test1.ru');
	$testCurlLine = $cookie->toCurl($testCookie['BITRIX_SM_GUEST_ID']);
	return $testCurlLine == ".test1.ru	TRUE	/	FALSE	1416569958	BITRIX_SM_GUEST_ID	87997";
}

function toFileCurl(){
	$cookie = new cCookie();
	$cookie->open(FILE_NAME);
	$cookie->create('PHPSESSID', '123456', '.test1.ru', '/', 0, true, false, true);
	$cookie->toFileCurl($cookie->getCookies('test1.ru'));
	$testCookie = $cookie->getCookies('test1.ru');
	return $testCookie['PHPSESSID']['value'] == '123456';
}

function delete(){
	$cookie = new cCookie();
	$cookie->open(FILE_NAME);
	$cookie->delete('test1.ru', 'PHPSESSID');
	$testCookie = $cookie->getCookies('test1.ru');
	return !isset($testCookie['PHPSESSID']);
}